### ISSUE TITLE
Attribute Error While Running

### ISSUE THREAD

**Issue by saja1994** [iliasprc/COVIDNet#8]
Thanks for your effort. When I tried to run the code I got the following error, How can I handle it?

Traceback (most recent call last):
  File "main.py", line 72, in <module>
    main()
  File "main.py", line 36, in main
    best_pred_loss = util.save_model(model, optimizer, args, val_metrics, epoch, best_pred_loss, confusion_matrix)
  File "/content/drive/My Drive/COVIDNet/utils/util.py", line 61, in save_model
    loss = metrics.data['loss']
AttributeError: 'MetricTracker' object has no attribute 'data'

**Comment by 15826694153** [comment]
I also met the same problem. Have you solved it

**Comment by hendrikTpl** [comment]
this version has not been finished yet, there's still a bug and some inconsistent code, especially when you try to customize it. 
in util.py the instance MetricTracker doesn't get the attribute "_data". I am not sure, you might start to debugging.
